### ISSUE TITLE
Environment not featured in navigation

### ISSUE THREAD

**Issue by SpazzMarticus** [slimphp/Slim-Website#120]
Hi,

I managed to find the documentation for the environment via this repository, but it seems that it isn't linked somewhere in the navigation.

[Environment](http://www.slimframework.com/docs/objects/environment.html)

Can you please add it?

**Comment by llvdl** [comment]
It seems that the menu item was removed when the navigation was reorganized on 17 August 2015: https://github.com/slimphp/Slim-Website/commit/b8b10d9ff4d1511c002ae03649782d4e95e7e110 

Maybe the menu item has been taken out, because the environment is a more advanced topic? If so, perhaps a menu item can be added under the section "Cook book", e.g. "Retrieving and Mocking the Environment"?
