### ISSUE TITLE
Confusing usage of Request Response object

### ISSUE THREAD

**Issue by Rotzbua** [slimphp/Slim-Website#267]
The documentation should be more clear about which `Response` or `Request` object is used. Especially the example with type hints are very confusing. E.g.:

```php
$app->get('/hello/{name}', function (Request $request, Response $response, $args) {
    $response->write("Hello, $name"); // sometimes work
    return $response;
}
```
The problem is, that `$response->write("Hello, $name");` is the Slim Object and not the PSR-7. So the suggested include to make it work is:
```php
use Slim\Http\Request;
use Slim\Http\Response;
```
But instead the PSR is used with an alias:
```php
use \Psr\Http\Message\ServerRequestInterface as Request;
use \Psr\Http\Message\ResponseInterface as Response;
```

**Comment by tflight** [comment]
`Psr\Http\Message\ServerRequestInterface` and `Psr\Http\Message\ResponseInterface` are not _objects_, rather they are _Interfaces_. Therefore if you type hint against `Psr\Http\Message\ServerRequestInterface` you can pass it **any** object that _implements_ the Interface. Since `Slim\Http\Request` [does implement that interface](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L33), you can pass the function a `Slim\Http\Request` object.

You can type hint against `Slim\Http\Request` instead of `Psr\Http\Message\ServerRequestInterface`, however then you are limited to passing in only `Slim\Http\Request` objects. Other objects that implement `Psr\Http\Message\ServerRequestInterface` couldn't be used.

**Comment by svpernova09** [comment]
Probably safe to close this issue.
