### ISSUE TITLE
Including setArgument to Route and Middleware docs

### ISSUE THREAD

**Issue by Johardmeier** [slimphp/Slim-Website#293]
I was looking for this and didn't find anything in the docs. We have **Passing variables from middleware** in the middleware section, but no **passing variables to the middleware**

**Comment by l0gicgate** [comment]
It is in the docs, Since the middleware gets the `Request` object, you can append attributes to it during the progression of the request using `Request::withAttribute($param, $value)`.

Another way you can pass data to your middleware is to pass it when you instantiate the middleware itself depending on if the `__construct()` function is being used or not for said middleware.
```php
$myMiddleware = new MyMiddleware($myData);
$app->add($myMiddleware);
```

@akrabat this can be closed.
