### ISSUE TITLE
CORS example is ambiguous in v4 documentation

### ISSUE THREAD

**Issue by vaga** [slimphp/Slim-Website#425]
```
// Pay attention to this when you are using some javascript front-end framework and you are using groups in slim php
$app->group('/api', function () {
    // Due to the behaviour of browsers when sending PUT or DELETE request, you must add the OPTIONS method. Read about preflight.
    $this->map(['PUT', 'OPTIONS'], '/{user_id:[0-9]+}', function ($request, $response, $arguments) {
        // Your code here...
    });
});

$app->run();
```
The comments of this part seems to be false:
- You should add OPTIONS method in all HTTP methods, not only PUT or DELETE.
- You should add OPTIONS method on all routes not only routes in group.

What do you think about that?

**Comment by odan** [comment]
> You should add OPTIONS method in all HTTP methods, not only PUT or DELETE.
> You should add OPTIONS method on all routes not only routes in group.

A preflight request is an **OPTIONS** request:

Mozilla[*](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests) says:
> Unlike simple requests, "preflighted" requests first send an HTTP request by the **OPTIONS** method to the resource on the other domain, to determine if the actual request is safe to send. 

For this reason, the **OPTIONS** method is also required for all CORS-specific routes and route groups.

**Edit:** IMHO The example in the documents is quite "dangerous" because a preflight request would trigger **the same callback** as the PUT method. This may lead to unwanted / duplicate / corrupted data in your database.

Instead the `OPTIONS` request needs a dedicated "null" route. Here is an example:

```php
// Pay attention to this when you are using some javascript front-end framework and you are using groups in slim php
$app->group('/api', function () {
    // Due to the behaviour of browsers when sending PUT or DELETE request, you must add the OPTIONS method. Read about preflight.
    $this->put('/{user_id:[0-9]+}', function ($request, $response, $arguments) {
        // Your code here...
    });
    $this->options('/{user_id:[0-9]+}', function ($request, $response) {
        // Do nothing, return just the response
        return $response;
    });
});
```
